---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fio-benchmark.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fio-benchmark.labels" . | nindent 4 }}
data:
  fio.job: |
{{ include "fio-benchmark.fioJobContent" . | indent 4 }}
